.TH "/home/lucio/Documentos/desenvolvimento/algoritmo_C/bibliotecas/static/libTimeTask/example/principal.c" 3 "Sun Apr 16 2017" "Version 1.0.00" "Library Time Task" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/lucio/Documentos/desenvolvimento/algoritmo_C/bibliotecas/static/libTimeTask/example/principal.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include 'ctrlTask\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcallBack_01\fP (void)"
.br
.ti -1c
.RI "void \fBcallBack_02\fP (void)"
.br
.ti -1c
.RI "void \fBcallBack_03\fP (void)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
: lucio
.RE
.PP
\fBDate:\fP
.RS 4
: 10 de Abril de 2013, 12:17 
.RE
.PP

.PP
Definition in file \fBprincipal\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void callBack_01 (void)"

.PP
Definition at line 24 of file principal\&.c\&.
.SS "void callBack_02 (void)"

.PP
Definition at line 42 of file principal\&.c\&.
.SS "void callBack_03 (void)"

.PP
Definition at line 60 of file principal\&.c\&.
.SS "int main (void)"

.PP
Definition at line 78 of file principal\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Library Time Task from the source code\&.
