.TH "stArrayTask" 3 "Sun Apr 16 2017" "Version 1.0.00" "Library Time Task" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stArrayTask \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBstTask_t\fP \fBtask\fP [\fBMAX_ELEMENTS\fP]"
.br
.ti -1c
.RI "uint8_t \fBnum_elements\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file ctrlTask\&.c\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t num_elements"
quantidade de elementos na lista 
.PP
Definition at line 38 of file ctrlTask\&.c\&.
.SS "\fBstTask_t\fP task[\fBMAX_ELEMENTS\fP]"
lista de tarefa a ser executada 
.PP
Definition at line 37 of file ctrlTask\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Library Time Task from the source code\&.
