.TH "stTask_t" 3 "Sun Apr 16 2017" "Version 1.0.00" "Library Time Task" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stTask_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBstTimeoutGeral_t\fP \fBstTimerGeral\fP"
.br
.ti -1c
.RI "uint32_t \fBcountTimer\fP"
.br
.ti -1c
.RI "uint32_t \fBvalueTimer\fP"
.br
.ti -1c
.RI "void(* \fBproc\fP )(void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file ctrlTask\&.c\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t countTimer"
contador de tempo 
.PP
Definition at line 31 of file ctrlTask\&.c\&.
.SS "void(* proc) (void)"
funcao que sera executada 
.PP
Definition at line 33 of file ctrlTask\&.c\&.
.SS "struct \fBstTimeoutGeral_t\fP stTimerGeral"
estrutura de tempo 
.PP
Definition at line 30 of file ctrlTask\&.c\&.
.SS "uint32_t valueTimer"
valor de intervalo em que a tarefa irá ser executada 
.PP
Definition at line 32 of file ctrlTask\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Library Time Task from the source code\&.
