.TH "stTimeoutGeral_t" 3 "Sun Apr 16 2017" "Version 1.0.00" "Library Time Task" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stTimeoutGeral_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <timer\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct timeval \fBStartTime\fP"
.br
.ti -1c
.RI "unsigned long int \fBTimeoutValue\fP"
.br
.ti -1c
.RI "unsigned long int \fBInitialized\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file timer\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned long int Initialized"
flag de controle se tempo foi inicializado ou nao 
.PP
Definition at line 28 of file timer\&.h\&.
.SS "struct timeval StartTime"
estrutura de tempo 
.PP
Definition at line 26 of file timer\&.h\&.
.SS "unsigned long int TimeoutValue"
valor de tempo a ser verificado 
.PP
Definition at line 27 of file timer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Library Time Task from the source code\&.
